version: "3.1"

services:
  bot:
    container_name: alchemist_tg_bot
    build:
      context: .
    command: python bot/bot.py
    restart: always
    networks:
      - batya_botnet
    env_file:
      - "bot/.env"
    volumes:
      - .:/src

  redis:
    container_name: redis_alchemist
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

networks:
  batya_botnet:
    external: true